name: Build Telegram 767 MOD Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Theos
      uses: kabiroberai/theos-action@v1
      with:
        sdk-url: "https://github.com/theos/sdks/releases/download/iPhoneOS16.5/iPhoneOS16.5.sdk.tar.xz"
        cache-key: theos-${{ runner.os }}

    - name: Build
      run: make package FINALPACKAGE=1 ARCHS=arm64

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: TelegramTweak767
        path: packages/*.deb
        if-no-files-found: warn
